'use strict';

require('dotenv').config();
const mongoose = require('mongoose');
const env = require('../src/config/env');
const GroceryCategory = require('../src/modules/grocery/groceryCategory.model');
const GroceryProduct = require('../src/modules/grocery/groceryProduct.model');
const GroceryBanner = require('../src/modules/grocery/groceryBanner.model');

const CATEGORIES_DATA = [
  {
    name: 'Fresh Vegetables',
    slug: 'fresh-vegetables',
    subtitle: 'Leafy greens, Root veggie...',
    badge: 'TOP OFFER',
    badgeType: 'lime',
    itemCount: '140+ items',
    emoji: '🥦',
    image: 'https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#F3F7F2',
    sortOrder: 1,
  },
  {
    name: 'Cooking Oils & Ghee',
    slug: 'cooking-oils-ghee',
    subtitle: 'Olive oil, Pure ghee,...',
    badge: 'POPULAR',
    badgeType: 'lime',
    itemCount: '95+ items',
    emoji: '🫒',
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=300',
    bg: '#F9F8F0',
    sortOrder: 2,
  },
  {
    name: 'Stationery & School',
    slug: 'stationery-school',
    subtitle: 'Notebooks, Pens, Sticky...',
    badge: 'OFFICE',
    badgeType: 'grey',
    itemCount: '60+ items',
    emoji: '✏️',
    image: 'https://images.pexels.com/photos/159832/pencil-education-school-supplies-159832.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#F5F5F7',
    sortOrder: 3,
  },
  {
    name: 'Fresh Fruits',
    slug: 'fresh-fruits',
    subtitle: 'Apples, Bananas, Berries,...',
    badge: 'BESTSELLER',
    badgeType: 'lime',
    itemCount: '80+ items',
    emoji: '🍎',
    image: 'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#FAF3F0',
    sortOrder: 4,
  },
  {
    name: 'Meat & Seafood',
    slug: 'meat-seafood',
    subtitle: 'Poultry, Fish fillet, Mutton',
    badge: 'FRESH DAILY',
    badgeType: 'pink',
    itemCount: '45+ items',
    emoji: '🥩',
    image: 'https://images.pexels.com/photos/65175/pexels-photo-65175.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#FDF2F2',
    sortOrder: 5,
  },
  {
    name: 'Dairy, Bread & Eggs',
    slug: 'dairy-bread-eggs',
    subtitle: 'Milk, Butter, Farm eggs,...',
    badge: 'MORNING',
    badgeType: 'grey',
    itemCount: '75+ items',
    emoji: '🥛',
    image: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#FFFDF0',
    sortOrder: 6,
  },
  {
    name: 'Snacks & Munchies',
    slug: 'snacks-munchies',
    subtitle: 'Chips, Biscuits, Chocolates',
    badge: 'TOP OFFER',
    badgeType: 'lime',
    itemCount: '120+ items',
    emoji: '🥨',
    image: 'https://images.pexels.com/photos/5765/food-red-sweet-fruit.jpg?auto=compress&cs=tinysrgb&w=300',
    bg: '#FDF7E8',
    sortOrder: 7,
  },
  {
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    subtitle: 'Soda, Fresh juices, Energy',
    badge: 'CHILLED',
    badgeType: 'grey',
    itemCount: '50+ items',
    emoji: '🥤',
    image: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=300',
    bg: '#F0F9F8',
    sortOrder: 8,
  },
];

const BANNERS_DATA = [
  {
    title: 'Up to 40% OFF',
    subtitle: 'On fresh fruits & daily farm harvest',
    code: 'FRESH40',
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=800',
    bgGradient: { from: '#1E3D34', to: '#142822' },
    linkType: 'category',
    targetId: 'fresh-fruits',
    sortOrder: 1,
  },
  {
    title: 'Organic Week Special',
    subtitle: 'Pure 100% certified pesticide-free greens',
    code: 'ORGANIC20',
    image: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800',
    bgGradient: { from: '#2E7D32', to: '#1B5E20' },
    linkType: 'category',
    targetId: 'organic-wellness',
    sortOrder: 2,
  },
];

async function seedGroceryData() {
  console.log('🛒 Seeding Grocery Data...');

  await Promise.all([
    GroceryCategory.deleteMany({}),
    GroceryProduct.deleteMany({}),
    GroceryBanner.deleteMany({}),
  ]);

  const createdCategories = await GroceryCategory.insertMany(CATEGORIES_DATA);
  const catMap = createdCategories.reduce((acc, cat) => {
    acc[cat.slug] = cat._id;
    return acc;
  }, {});

  await GroceryBanner.insertMany(BANNERS_DATA);

  const PRODUCTS_DATA = [
    // Fruits & Deals
    {
      name: 'Organic Cavendish Banana',
      slug: 'organic-banana',
      category: catMap['fresh-fruits'],
      price: 1.5,
      originalPrice: 2.2,
      unit: '/bunch',
      images: ['https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'deal',
      discount: '30% off',
      rating: 4.8,
      ratingCount: 124,
      isSpecialDeal: true,
      isOrganic: true,
      stockQuantity: 200,
      tags: ['banana', 'fruit', 'organic', 'potassium'],
    },
    {
      name: 'Baby Spinach Fresh',
      slug: 'baby-spinach-fresh',
      category: catMap['fresh-vegetables'],
      price: 3.4,
      originalPrice: 4.5,
      unit: '/bunch',
      images: ['https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'best_seller',
      rating: 4.9,
      ratingCount: 310,
      isSpecialDeal: true,
      isOrganic: true,
      isTrending: true,
      stockQuantity: 150,
      tags: ['spinach', 'greens', 'organic', 'vegetable'],
    },
    {
      name: 'Red Royal Gala Apples',
      slug: 'red-gala-apples',
      category: catMap['fresh-fruits'],
      price: 2.8,
      originalPrice: 3.5,
      unit: '/kg',
      images: ['https://images.pexels.com/photos/672101/pexels-photo-672101.jpeg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'organic',
      discount: '20% off',
      rating: 4.7,
      ratingCount: 89,
      isSpecialDeal: true,
      isOrganic: true,
      stockQuantity: 180,
      tags: ['apple', 'fruits', 'sweet', 'organic'],
    },
    {
      name: 'Fresh Farm Broccoli',
      slug: 'fresh-farm-broccoli',
      category: catMap['fresh-vegetables'],
      price: 1.9,
      originalPrice: 2.5,
      unit: '/piece',
      images: ['https://images.pexels.com/photos/1078018/pexels-photo-1078018.jpeg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'organic',
      rating: 4.6,
      ratingCount: 75,
      isSpecialDeal: true,
      isOrganic: true,
      stockQuantity: 90,
      tags: ['broccoli', 'vegetable', 'healthy'],
    },

    // Seafood & Fresh Salmon
    {
      name: 'Fresh Salmon Fillet',
      slug: 'fresh-salmon-fillet',
      category: catMap['meat-seafood'],
      price: 2.4,
      unit: '/pack',
      weightInfo: 'Approx. 200g - 250g | Wild Caught',
      estimatedDelivery: 'Today 5–6PM',
      description:
        'Rich in protein and omega-3, this premium cut is not only nutritious but also delicious. Perfect for grilling, pan-searing, or baking with herbs and citrus.',
      images: ['https://images.pexels.com/photos/3296279/pexels-photo-3296279.jpeg?auto=compress&cs=tinysrgb&w=800'],
      badge: 'best_seller',
      rating: 4.9,
      ratingCount: 128,
      isSpecialDeal: true,
      isTrending: true,
      stockQuantity: 40,
      highlights: [
        { label: 'High protein', type: 'lime', icon: 'barbell-outline' },
        { label: 'Omega-3 rich', type: 'blue', icon: 'water-outline' },
        { label: 'Organic', type: 'grey', icon: 'leaf-outline' },
      ],
      tags: ['salmon', 'fish', 'seafood', 'protein', 'fillet'],
    },
    {
      name: 'Lemon',
      slug: 'fresh-lemon',
      category: catMap['fresh-fruits'],
      price: 0.99,
      unit: '/each',
      images: ['https://images.pexels.com/photos/1414110/pexels-photo-1414110.jpeg?auto=compress&cs=tinysrgb&w=300'],
      rating: 4.8,
      ratingCount: 55,
      stockQuantity: 150,
      tags: ['lemon', 'citrus', 'fruit'],
    },
    {
      name: 'Herb Mix',
      slug: 'fresh-herb-mix',
      category: catMap['fresh-vegetables'],
      price: 0.99,
      unit: '/each',
      images: ['https://images.pexels.com/photos/4198024/pexels-photo-4198024.jpeg?auto=compress&cs=tinysrgb&w=300'],
      rating: 4.7,
      ratingCount: 40,
      stockQuantity: 90,
      tags: ['herbs', 'rosemary', 'seasoning'],
    },
    {
      name: 'Extra Virgin Olive Oil',
      slug: 'extra-virgin-olive-oil',
      category: catMap['cooking-oils-ghee'],
      price: 7.5,
      originalPrice: 8.8,
      unit: '500ml bottle',
      images: ['https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'deal',
      discount: '15% OFF',
      rating: 4.8,
      ratingCount: 94,
      isOrganic: true,
      isSpecialDeal: true,
      stockQuantity: 120,
      tags: ['oil', 'olive oil', 'cooking oil', 'cold pressed'],
    },
    {
      name: 'Pure Cow Ghee',
      slug: 'pure-cow-ghee',
      category: catMap['cooking-oils-ghee'],
      price: 8.9,
      originalPrice: 10.0,
      unit: '500g glass jar',
      images: ['https://images.pexels.com/photos/4198024/pexels-photo-4198024.jpeg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'best_seller',
      rating: 4.9,
      ratingCount: 180,
      isSpecialDeal: true,
      isTrending: true,
      stockQuantity: 85,
      tags: ['ghee', 'dairy', 'pure ghee', 'cow ghee'],
    },
    {
      name: 'Organic Mustard Oil',
      slug: 'organic-mustard-oil',
      category: catMap['cooking-oils-ghee'],
      price: 4.2,
      unit: '1L bottle',
      images: ['https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=400'],
      badge: 'organic',
      rating: 4.6,
      ratingCount: 52,
      isOrganic: true,
      stockQuantity: 90,
      tags: ['mustard oil', 'cooking oil', 'organic oil'],
    },
    {
      name: 'Canola & Sunflower Oil',
      slug: 'canola-sunflower-oil',
      category: catMap['cooking-oils-ghee'],
      price: 3.8,
      originalPrice: 4.5,
      unit: '1L container',
      images: ['https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=400'],
      discount: 'Everyday Value',
      rating: 4.5,
      ratingCount: 68,
      stockQuantity: 150,
      tags: ['canola', 'sunflower oil', 'cooking oil'],
    },
    {
      name: 'Cold Pressed Coconut Oil',
      slug: 'cold-pressed-coconut-oil',
      category: catMap['cooking-oils-ghee'],
      price: 6.1,
      unit: '500ml jar',
      images: ['https://images.pexels.com/photos/4198024/pexels-photo-4198024.jpeg?auto=compress&cs=tinysrgb&w=400'],
      discount: 'Cold Pressed',
      rating: 4.9,
      ratingCount: 112,
      isOrganic: true,
      stockQuantity: 70,
      tags: ['coconut oil', 'cold pressed', 'organic'],
    },
    {
      name: 'Sesame Cooking Oil',
      slug: 'sesame-cooking-oil',
      category: catMap['cooking-oils-ghee'],
      price: 4.5,
      unit: '250ml bottle',
      images: ['https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=400'],
      rating: 4.7,
      ratingCount: 43,
      stockQuantity: 65,
      tags: ['sesame oil', 'cooking oil'],
    },

    // Trending Items
    {
      name: 'Sweet Cherry Tomatoes',
      slug: 'sweet-cherry-tomatoes',
      category: catMap['fresh-vegetables'],
      price: 0.85,
      originalPrice: 1.45,
      unit: '290g pack',
      images: ['https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=400'],
      discount: '40% off',
      rating: 4.8,
      ratingCount: 220,
      isTrending: true,
      stockQuantity: 140,
      tags: ['tomatoes', 'cherry tomato', 'salad'],
    },
    {
      name: 'Fresh Chicken Breast Fillet',
      slug: 'chicken-fillet-fresh',
      category: catMap['meat-seafood'],
      price: 8.22,
      originalPrice: 14.22,
      unit: '500g',
      images: ['https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=400'],
      discount: '40% off',
      badge: 'best_seller',
      rating: 4.9,
      ratingCount: 450,
      isTrending: true,
      stockQuantity: 80,
      tags: ['chicken', 'meat', 'protein', 'poultry'],
    },
    {
      name: 'Artisan Strawberry Jam',
      slug: 'artisan-strawberry-jam',
      category: catMap['snacks-munchies'],
      price: 1.22,
      originalPrice: 1.8,
      unit: '320ml jar',
      images: ['https://images.pexels.com/photos/5765/food-red-sweet-fruit.jpg?auto=compress&cs=tinysrgb&w=400'],
      rating: 4.5,
      ratingCount: 62,
      isTrending: true,
      stockQuantity: 60,
      tags: ['jam', 'strawberry', 'spread', 'breakfast'],
    },
    {
      name: 'Red Cabbage Premium Harvest',
      slug: 'red-cabbage-premium',
      category: catMap['fresh-vegetables'],
      price: 4.1,
      unit: '1 pc',
      images: ['https://images.pexels.com/photos/2893635/pexels-photo-2893635.jpeg?auto=compress&cs=tinysrgb&w=400'],
      rating: 4.4,
      ratingCount: 38,
      isTrending: true,
      stockQuantity: 50,
      tags: ['cabbage', 'red cabbage', 'salad'],
    },
    {
      name: 'Greek Style Plain Yogurt',
      slug: 'greek-style-yogurt',
      category: catMap['dairy-bread-eggs'],
      price: 2.5,
      originalPrice: 3.8,
      unit: '400g tub',
      images: ['https://images.pexels.com/photos/1394085/pexels-photo-1394085.jpeg?auto=compress&cs=tinysrgb&w=400'],
      discount: '35% off',
      badge: 'best_seller',
      rating: 4.9,
      ratingCount: 310,
      isTrending: true,
      stockQuantity: 110,
      tags: ['yogurt', 'dairy', 'probiotic', 'greek'],
    },
    {
      name: 'Mixed Bell Peppers Trio',
      slug: 'mixed-bell-peppers-trio',
      category: catMap['fresh-vegetables'],
      price: 1.8,
      unit: '3 pack',
      images: ['https://images.pexels.com/photos/594137/pexels-photo-594137.jpeg?auto=compress&cs=tinysrgb&w=400'],
      rating: 4.6,
      ratingCount: 94,
      isTrending: true,
      stockQuantity: 95,
      tags: ['peppers', 'capsicum', 'vegetables'],
    },
  ];

  await GroceryProduct.insertMany(PRODUCTS_DATA);
  console.log(`✅ Seeded ${createdCategories.length} categories and ${PRODUCTS_DATA.length} grocery products.`);
}

if (require.main === module) {
  mongoose
    .connect(env.db.uri)
    .then(() => seedGroceryData())
    .then(() => {
      console.log('🎉 Grocery Seeding Complete!');
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Error during grocery seed:', err);
      process.exit(1);
    });
}

module.exports = { seedGroceryData };
