'use strict';

/**
 * constants/errorCodes.js — Machine-readable error codes.
 *
 * These codes are sent in API error responses as `code` field.
 * Clients can use these for localisation or specific error handling
 * without parsing human-readable messages.
 */

const ERROR_CODES = Object.freeze({
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Orders
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  CART_EMPTY: 'CART_EMPTY',
  CART_MIXED_RESTAURANT: 'CART_MIXED_RESTAURANT',
  ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',

  // Payments
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // Coupons
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_MIN_ORDER: 'COUPON_MIN_ORDER',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
});

module.exports = ERROR_CODES;
