'use strict';

const ERROR_CODES = Object.freeze({
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  STEP_UP_AUTH_REQUIRED: 'STEP_UP_AUTH_REQUIRED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Order & State Machine
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  INVALID_ACTOR_TRANSITION: 'INVALID_ACTOR_TRANSITION',
  STALE_VERSION: 'STALE_VERSION',
  CART_EMPTY: 'CART_EMPTY',
  CART_MIXED_RESTAURANT: 'CART_MIXED_RESTAURANT',
  ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  VENDOR_CLOSED: 'VENDOR_CLOSED',
  VENDOR_PAUSED: 'VENDOR_PAUSED',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',

  // Verticals & Settings
  VERTICAL_UNAVAILABLE: 'VERTICAL_UNAVAILABLE',
  VERTICAL_DRAINING: 'VERTICAL_DRAINING',

  // Payments & Refunds
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  REFUND_FAILED: 'REFUND_FAILED',
  REFUND_APPROVAL_REQUIRED: 'REFUND_APPROVAL_REQUIRED',

  // Coupons
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_MIN_ORDER: 'COUPON_MIN_ORDER',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  LOCK_ACQUISITION_FAILED: 'LOCK_ACQUISITION_FAILED',
});

module.exports = ERROR_CODES;
