'use strict';

const ERROR_CODES = Object.freeze({
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  CART_EMPTY: 'CART_EMPTY',
  CART_MIXED_RESTAURANT: 'CART_MIXED_RESTAURANT',
  ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',

  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_MIN_ORDER: 'COUPON_MIN_ORDER',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
});

module.exports = ERROR_CODES;
