'use strict';

const ROLES = Object.freeze({
  CUSTOMER: 'customer',
  MERCHANT_OWNER: 'merchant_owner',
  MERCHANT_STAFF: 'merchant_staff',
  DELIVERY_PARTNER: 'delivery_partner',
  SUPER_ADMIN: 'super_admin',
  OPS_ADMIN: 'ops_admin',
  CATALOG_ADMIN: 'catalog_admin',
  SUPPORT_ADMIN: 'support_admin',
  FINANCE_ADMIN: 'finance_admin',
  // Backward-compatibility aliases
  RESTAURANT_OWNER: 'restaurant_owner',
  ADMIN: 'admin',
});

const PERMISSIONS = Object.freeze({
  CATALOG_WRITE: 'catalog:write',
  CATALOG_READ: 'catalog:read',
  ORDER_VIEW: 'order:view',
  ORDER_OVERRIDE: 'order:override',
  ORDER_MANAGE: 'order:manage',
  VERTICAL_TOGGLE: 'vertical:toggle',
  REFUND_APPROVE: 'refund:approve',
  VENDOR_APPROVE: 'vendor:approve',
  VENDOR_MANAGE: 'vendor:manage',
  RIDER_MANAGE: 'rider:manage',
  SETTLEMENT_MANAGE: 'settlement:manage',
  ADMIN_MANAGE: 'admin:manage',
  AUDIT_READ: 'audit:read',
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.CUSTOMER]: [],
  [ROLES.MERCHANT_OWNER]: [PERMISSIONS.CATALOG_WRITE, PERMISSIONS.CATALOG_READ, PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_MANAGE],
  [ROLES.MERCHANT_STAFF]: [PERMISSIONS.CATALOG_READ, PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_MANAGE],
  [ROLES.DELIVERY_PARTNER]: [PERMISSIONS.ORDER_VIEW],
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.OPS_ADMIN]: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_OVERRIDE,
    PERMISSIONS.ORDER_MANAGE,
    PERMISSIONS.VERTICAL_TOGGLE,
    PERMISSIONS.VENDOR_APPROVE,
    PERMISSIONS.VENDOR_MANAGE,
    PERMISSIONS.RIDER_MANAGE,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.CATALOG_ADMIN]: [PERMISSIONS.CATALOG_WRITE, PERMISSIONS.CATALOG_READ, PERMISSIONS.VENDOR_MANAGE],
  [ROLES.SUPPORT_ADMIN]: [PERMISSIONS.ORDER_VIEW, PERMISSIONS.REFUND_APPROVE, PERMISSIONS.AUDIT_READ],
  [ROLES.FINANCE_ADMIN]: [PERMISSIONS.ORDER_VIEW, PERMISSIONS.REFUND_APPROVE, PERMISSIONS.SETTLEMENT_MANAGE, PERMISSIONS.AUDIT_READ],
  // Legacy aliases
  [ROLES.RESTAURANT_OWNER]: [PERMISSIONS.CATALOG_WRITE, PERMISSIONS.CATALOG_READ, PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_MANAGE],
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
});

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
